language: python
python:
  - '3.8'
install:
  - pip install -e .
script:
  - python -m unittest discover -s tests
deploy:
  provider: pypi
  user: "retxxxirt"
  password:
    secure: "RdNGFcSMtYnBVfnXztV7LxbhvjQJmPi4PUpejkkqyHSPEn95P+Xm1srqFHQvPvvGTmnBYYxilJTkRP2uikrl18EKO3Ry1y2YUUNJeN+7IbvtcHEpqKdOv3vgeFIDUeJBRpvBwoTyx0pN1GDHZC3nCqpKIuI7REvEmxtaV+fx0F0YWWBE7BffIQzb/1lze5vUd1VB4s2taNCnCRcM9XGcaoydHOdsBXmTnljCxhBndSVuROkNZVIpi59XeMfwws9HfBXDXmsXmJd87izKuAfGAwWUUSLTfCiSXn7uAAtGRWucZqFpUedeQm4B8Cg0cRJskb2KtZsnFzGPEiA1pVzFrF2e+GzsdoJIa4tWZLUR1ZSgbK5IBSroCGSym+6M/saTMOGsVW5Q+G1zAs75VFdMvJHi2G/80I4Z+6U3kkyj4dezLy1ENMuJcLLWD0/T17hhijTGViJtYgNyetpSjFAr3Z9chVW8UOj07PY6Gp2FVGd1fy6b8Q/COftON7LhFWn8fIQlppuQOZdAbur+geVBJC9PASLNBSzlg9wInoDKCJ1Po0A9avAKkP8WObnaAzzWOmmHI8ZrsYOf/0ssSSWZfdC8wS7ZdcCJuIGc2yfdvvwKb7NOVi1GIxyf4cTBeOXIDT8qBUSMBgwzMCXsHzkeLKIYxxo0h6S0ssCA4lmtET4="
  on:
    branch: production